export const FETCH_REQUEST_COUNTRIES = 'FETCH_REQUEST_COUNTRIES';
export const FETCH_SUCCESS_COUNTRIES = 'FETCH_SUCCESS_COUNTRIES';
export const FETCH_FAILURE_COUNTRIES = 'FETCH_FAILURE_COUNTRIES';
export const FILTER_COUNTRIES_ARRAY = 'FILTER_COUNTRIES_ARRAY';
export const EDIT_COUNTRY = 'EDIT_COUNTRY';
